[workspace]
members = [
    "parcel-common",
    "parcel-proxy",
    "parcel-server",
    "parcel-client/client-injector",
    "parcel-client/parcel-client",
    "re-testing/deobfuscate_json",
    "parcel-save-tool",
    "parcel-hashes",
]
