// AUTO-GENERATED by typescript-type-def

export type Provider = "steam" | "epic";
export type AuthRequest = { provider: Provider };
export type InitAuthResponse = { redirectUrl: string };
export type CheckAuthRequest = { callbackToken: string };
export type CheckAuthResponse =
  | { success: { name: string; avatarUrl: string; authToken: string } }
  | { failure: { error: string } };
export type I64 = number;
export type JwtPayload = { expiresAt: I64; accountId: string };
