// AUTO-GENERATED by typescript-type-def

export type Provider=("steam"|"epic");
export type AuthRequest={"provider":Provider;};
export type InitAuthResponse={"redirectUrl":string;};
export type CheckAuthRequest={"callbackToken":string;};
export type JwtPermissions="None";
export type CheckAuthResponse=(({"type":"success";}&{"name":string;"avatarUrl":string;"authToken":string;"permissions":JwtPermissions;})|({"type":"failure";}&{"error":string;}));
export type I64=number;
export type JwtPayload={"expiresAt":I64;"accountId":string;};
export type I32=number;
export type SharedCargoListItem={"name":string;"amount":I32;"category":string;"location":string;"creator":string;};
export type ListSharedCargoResponse={"baggages":(SharedCargoListItem)[];};
export type LostCargoListItem={"name":string;"amount":I32;"category":string;"location":string;"endLocation":string;"creator":string;};
export type ListLostCargoResponse={"baggages":(LostCargoListItem)[];};
export type WastedCargoListItem={"name":string;"category":string;"broken":boolean;"location":string;"creator":string;};
export type ListWastedCargoResponse={"baggages":(WastedCargoListItem)[];};
