CREATE TABLE account_histories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id VARCHAR NOT NULL REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    encountered_id VARCHAR NOT NULL REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    encountered_at TIMESTAMP NOT NULL
);

CREATE INDEX account_histories_created_at_idx ON account_histories (encountered_at DESC);

CREATE UNIQUE INDEX account_histories_id_account_id_idx ON account_histories (account_id, encountered_id);

CREATE TABLE account_strand_contracts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    owner_account_id VARCHAR NOT NULL REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    contract_account_id VARCHAR NOT NULL REFERENCES accounts(id) ON DELETE CASCADE ON UPDATE CASCADE,
    created_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX account_strand_contracts_owner_account_id_contract_account_id_idx ON account_strand_contracts (owner_account_id, contract_account_id);