name: Build and publish GitHub release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-pc-windows-msvc
      - name: Cache PostgreSQL
        id: cache-pgsql
        uses: actions/cache@v3
        with:
          path: /temp/pgsql
          key: pgsql-win-x64-15.3.1
      - name: Download PostgreSQL binaries
        if: steps.cache-pgsql.outputs.cache-hit != 'true'
        uses: suisei-cn/actions-download-file@v1.4.0
        with:
          url: https://get.enterprisedb.com/postgresql/postgresql-15.3-1-windows-x64-binaries.zip
          target: /temp/pg-dl/
          filename: pg.zip
      - name: Extract PostgreSQL binaries
        if: steps.cache-pgsql.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          Expand-Archive -Path /temp/pg-dl/pg.zip -DestinationPath /temp/
      - name: Add PostgreSQL lib folder to PATH
        shell: powershell
        run: |
          $pg_lib_dir = (Resolve-Path /temp/pgsql/lib).Path
          echo $pg_lib_dir >> $env:GITHUB_PATH
          echo $pg_lib_dir
          cat $env:GITHUB_PATH
      #- name: Build parcel-server
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: build
      #    args: --release -p parcel-server --target x86_64-pc-windows-msvc
      #- name: Build parcel-thief
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: build
      #    args: --release -p parcel-thief --target x86_64-pc-windows-msvc
      #- name: Install windows nightly toolchain
      #  uses: actions-rs/toolchain@v1
      #  with:
      #    toolchain: nightly-2023-05-21-x86_64-pc-windows-msvc # nightly needed for injector
      #    override: true
      #- name: Build parcel-injector
      #  uses: actions-rs/cargo@v1
      #  with:
      #    command: build
      #    args: --release -p parcel-injector --target x86_64-pc-windows-msvc
  build-linux:
    runs-on: ubuntu-latest
    if: ${{ false }} # Disable job while getting windows build to work
    steps:
      - uses: actions/checkout@v3
      - name: Install cargo toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
      - name: Build parcel-server for Linux 64-bit
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release -p parcel-server --target x86_64-unknown-linux-gnu
